apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-agent-app-deployment
  labels:
    app: angular-agent-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-agent-app
  template:
    metadata:
      labels:
        app: angular-agent-app
    spec:
      containers:
        - name: angular-agent-app
          image: vadimpastushenko7/tinysd-ui:${IMAGE_TAG}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-agent-app-service
spec:
  type: NodePort
  selector:
    app: angular-agent-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
