name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-git-version:
    runs-on: ubuntu-latest
    outputs:
      GIT_VERSION: ${{ steps.get_version.outputs.GIT_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get git version
        id: get_version
        run: |
          git fetch --tags
          GIT_VERSION=$(git describe --tags --abbrev=0)
          echo "GIT_VERSION=$GIT_VERSION" >> $GITHUB_OUTPUT

      - name: Use the tag
        run: echo "Latest tag is ${{ steps.get_version.outputs.GIT_VERSION }}"

  build-api:
    runs-on: ubuntu-latest
    needs: get-git-version
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: tinysd-api

      - name: Build NestJS API
        run: npm run build
        working-directory: tinysd-api

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./tinysd-api
          file: ./tinysd-api/Dockerfile
          push: true
          tags: vadimpastushenko7/tinysd-api:${{ needs.get-git-version.outputs.GIT_VERSION }}

  build-ui:
    runs-on: ubuntu-latest
    needs: get-git-version
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: tinysd-ui

      - name: Build Angular app
        run: npm run build:production
        working-directory: tinysd-ui

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push UI Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./tinysd-ui
          file: ./tinysd-ui/Dockerfile
          push: true
          tags: vadimpastushenko7/tinysd-ui:${{ needs.get-git-version.outputs.GIT_VERSION }}

  deploy-on-vm:
    runs-on: self-hosted
    needs:
      - build-api
      - build-ui
      - get-git-version
    steps:
      - name: Deploy to Kubernetes cluster on VM
        run: |
          envsubst < k8s-app.yaml | kubectl apply -f -
        env:
          IMAGE_TAG: ${{ needs.get-git-version.outputs.GIT_VERSION }}
